### ISSUE TITLE
ZGrab fails to decode cert that uses a different or older DER format for Boolean values

### ISSUE THREAD

**Issue by sviehb** [zmap/zgrab#180] opened 2016-09-05 11:11 UTC
The following certificate is not found in Censys search, however there are hosts on the web that use the certificate (HTTPS): https://github.com/google/certificate-transparency/blob/master/python/ct/crypto/testdata/matrixssl_sample.pem 

As Censys is fed by ZGrab I think there issue with parsing this certificate. Google chose it in their CT code test cases, see the comment below:
https://github.com/google/certificate-transparency/blob/master/python/ct/crypto/cert_test.py

``` python
# A old but common (0.5% of all certs as of 2013-10-01) SSL
# cert that uses a different or older DER format for Boolean
# values.
_PEM_MATRIXSSL = "matrixssl_sample.pem"
```

**Comment by zakird** [comment] 2016-09-06 05:11
I can confirm that this isn't correctly handled in zgrab right now:
```
zakir:zcertificate (master)$ ./zcertificate test 
FATAL: Unable to parse certificate:  asn1: syntax error: invalid boolean
```

**Comment by zakird** [comment] 2016-09-06 05:18
@kumarde I'm going to assign this to you as this is something that should be handled by zlint.

**Comment by kumarde** [comment] 2016-09-06 23:55
Hi @sviehb,

Do you know what exactly a "different or older DER format for Boolean values" looks like? My understanding is that DER encoding is very explicit about Boolean values - the octet value is all 0s (0x00) for false and all 1s (0xFF) for true. 

A cursory glance at the certificate parsing leads me to believe that there is a Boolean encoded with value 0x01, which, by my understanding, is actually an incorrect DER Boolean. I'm still looking to see if there was some ambiguity in the ASN.1 parsing on our side, but I just wanted to reach out and see what your thoughts were.

Thanks for your help!

**Comment by dadrian** [comment] 2016-09-07 03:28
If I had to take a guess, I've encountered this before, and OpenSSL takes it. I think the Golang parser is more strict.

https://github.com/dadrian/golang-asn1bug

**Comment by kumarde** [comment] 2016-09-07 15:10
@dadrian If that's the case, the certificate in question isn't technically RFC compliant, because the data should be DER encoded (RFC 5280: 4.1). Any thoughts on how to proceed? If we want to support parsing for this, I think we'll need to modify the asn1 encoding library provided by Golang.

**Comment by dadrian** [comment] 2016-09-07 15:29
https://github.com/golang/go/issues/11091

**Comment by dadrian** [comment] 2016-09-07 15:29
Do we have stats on how common this is?

**Comment by kumarde** [comment] 2016-09-07 15:36
@dadrian There's an effort by the zlint team to lint/check all the certificates in the censys store for RFC compliance. Once that runs, I guess we'll have a better picture of if this happens a lot in the wild.

**Comment by zakird** [comment] 2016-09-07 15:37
Unfortunately, I don't think that we will. This error is happening early enough that we're never able to parse the certificate and therefore I don't think it'll ever end up in the certificate store.

**Comment by zakird** [comment] 2016-09-07 15:46
If we want to truly know how pervasive this and other certificate parsing errors are, we should go through all of the certificates in the CT logs that we are not able to import into Censys and figure out the root cause for being unable to parse them.

**Comment by dadrian** [comment] 2016-09-07 16:02
Well, I _really_ don't want to fork Golang's ASN.1 library, and it doesn't look like Adam will accept a PR to Golang stdlib unless we can show this is common, so I vote we table this for now, unless someone really wants to categorize every parse error for certificates in CT, and certificates in a recent HTTPS scan of IPv4.

**Closed** 2020-06-30 15:34 UTC
Labels: bug
